server:
  port: ${PORT:8080}

spring:
  application:
    name: customer-producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        prompt-delivery-exchange-order-created-output:
          destination: customer
          group: ${spring.application.name}



