spring:
  application:
    name: spring-cloud-multi-binder
  cloud:
    stream:
      bindings:
        person-created-output:
          destination: person.created
          content-type: application/json
          binder: kafka
        person-created-input:
          destination: person.created
          content-type: application/json
          group: ${spring.application.name}
          binder: kafka
        notify-registration-departament-output:
          destination: notify-registration-departament
          content-type: application/json
          binder: rabbit
        notify-registration-departament-input:
          destination: notify-registration-departament
          content-type: application/json
          group: ${spring.application.name}
          binder: rabbit
      kafka:
        binder:
          brokers: localhost:9092
      rabbit:
        bindings:
          notify-registration-departament-input:
            consumer:
              auto-bind-dlq: true
    rabbitmq:
      addresses: localhost:5672
      username: guest
      password: guest
      virtual-host: "/"

