server:
  port: ${PORT:8081}

spring:
  application:
    name: customer-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        customer-input:
          destination: customer
          group: ${spring.application.name}



