server:
  port: ${PORT:8082}

spring:
  application:
    name: customer-translator
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        customer-input:
          destination: customer
          group: ${spring.application.name}
          consumer:
            useNativeDecoding: true
        vip-customer-output:
          destination: vip-customer
          producer:
            useNativeEncoding: true
logging:
  level:
    org.springframework.kafka.config: debug